### ISSUE TITLE
cuda out of memory when predicting

### ISSUE THREAD

**Issue by Theodoric008** [TAMU-VITA/EnlightenGAN#11]
its ok when training, but cuda out of memory when predicting, how to adjust paramters?

**Comment by Theodoric008** [comment]
by the way, i got some result, and it is absolutely IMPRESSIVE

**Comment by yueruchen** [comment]
Hi, thanks for following our work.
Actually, I used a very wide model which is not necessary. if you want to use it for high-resolution image you could try to train a small-size model.

**Comment by yueruchen** [comment]
Or resize the input model to a low-resolution one and use guided image filtering (http://kaiminghe.com/publications/eccv10guidedfilter.pdf) to get a high-resolution output.

**Comment by UtopiaHu** [comment]
I met the same problem when I used your provided model to test on some images of your provided testing datasets. How can I make some adjustments if I have only 1 1080ti GPU card?

**Comment by yueruchen** [comment]
@UtopiaHu Try to resize the input images to half size.
