### ISSUE TITLE
pretrained model problems

### ISSUE THREAD

**Issue by fengchaoyu1** [TAMU-VITA/EnlightenGAN#16]
Could you share your config and experiment parameters of your pretrained model? I can not use your pretrained model to test photos directly.  And could you share your supplementary materials which mentioned in your paper?

**Comment by yueruchen** [comment]
Sorry for late reply, but the training script is already included in the repo. You should get the expected results given you have at least 3 1080ti gpus. (The experiment requires batchs size larger than 32)
