### ISSUE TITLE
The artifact problem

### ISSUE THREAD

**Issue by zhengziqiang** [TAMU-VITA/EnlightenGAN#21]
I followed your instructions and the results have some artifacts, especially the clean images. 
![image](https://user-images.githubusercontent.com/18065488/62918838-76c6cd00-bdd3-11e9-9d77-c638560d3c20.png)

**Comment by yueruchen** [comment]
Is this result produced by our pretrained model? We do not observe these artifacts before.

**Comment by zhengziqiang** [comment]
I just train the model using the provided datasets using the default parameters except set batchsize 1. Could this be the cause of the problem?

**Comment by yueruchen** [comment]
Batch size should be no less than 8

**Comment by zhengziqiang** [comment]
OK, I will close this issue. Thank you.
