### ISSUE TITLE
关于RGAN损失的疑问

### ISSUE THREAD

**Issue by sibangde** [TAMU-VITA/EnlightenGAN#22]
您好，论文中提到利用的是RGAN格式的损失函数，但我在代码中没有找到，您能指出一下在哪里吗，谢谢~

**Comment by yueruchen** [comment]
https://github.com/TAMU-VITA/EnlightenGAN/blob/3828679c6e4c9524cb99e46d544976a257bafe4d/models/single_model.py#L288
