### ISSUE TITLE
I get some problem when I use your train_data for enlightening.

### ISSUE THREAD

**Issue by hw331** [TAMU-VITA/EnlightenGAN#23]
When I use your training dataset to predict, the color of the image in the predicted result does not look normal. I don't know if the training data is used to predict whether it is correct.

**Comment by yueruchen** [comment]
Could you please upload some results?

**Comment by hw331** [comment]
![203_10_real_A](https://user-images.githubusercontent.com/42433513/64486157-0db06900-d25c-11e9-8fa2-f3721c888cb8.png)
![203_10_fake_B](https://user-images.githubusercontent.com/42433513/64486159-11dc8680-d25c-11e9-9e4e-a3dbc3448168.png)
![213_2_real_A](https://user-images.githubusercontent.com/42433513/64486164-215bcf80-d25c-11e9-9344-d7e53287480e.png)

**Comment by hw331** [comment]
![262A0981_fake_B](https://user-images.githubusercontent.com/42433513/64486384-122a5100-d25f-11e9-8b87-266a705de560.png)
![262A0981_real_A](https://user-images.githubusercontent.com/42433513/64486388-1e161300-d25f-11e9-9952-ba9099a42c52.png)
![6_2_fake_B](https://user-images.githubusercontent.com/42433513/64486442-e196e700-d25f-11e9-9136-5bb7ccae2960.png)
![6_2_real_A](https://user-images.githubusercontent.com/42433513/64486443-e5c30480-d25f-11e9-917f-01e908b2d384.png)

**Comment by yueruchen** [comment]
I think it is not the color problem but the lighting problem. We don't try it on training data directly. But of course, there is some bad case and these are some of them. If you can collect more data it will help.
