### ISSUE TITLE
Large image(3840*2160) raise RuntimeError: CUDA error: out of memory. 

### ISSUE THREAD

**Issue by genausz** [TAMU-VITA/EnlightenGAN#26]
Hello, if there are any solutions for the case that input image are way too large which will raise OOM Error one RTX 2080 Ti.
In my case, the input image size is 3840*2160.
Thanks.

**Comment by yueruchen** [comment]
You may consider to retrain a model with fewer parameters (such as decreasing channel number) or resize the current image to small resolution and resize the output to original resolution by bilinear or bilateral upsample.
