### ISSUE TITLE
Failed to download datasets

### ISSUE THREAD

**Issue by YHLelaine** [TAMU-VITA/EnlightenGAN#28]
Dear researchers, I am sorry to say that I failed to download the datasets for training and predicting. Before that, I have gotten the other materials except datasets.
Could you please provide other mothods to download datasets? I am looking forward.

**Comment by YHLelaine** [comment]
With the help of other researchers, I succeeded downloading the datasets for EnlightenGAN. Now, I packed them again and upload them to BaiduNetDisk Again. New link is listed below.
If necessary, contact with me via fluenceyhl@163.com.

链接：https://pan.baidu.com/s/18JttbhCd5BrMBj_ks-TXNg 
提取码：k4cb 
复制这段内容后打开百度网盘手机App，操作更方便哦

**Comment by yueruchen** [comment]
Thanks!

**Comment by hermosayhl** [comment]
The old link is updated below:
链接：https://pan.baidu.com/s/1122P2qvdN_OpOFg1CaLUHg 
提取码：xlz3

**Comment by hermosayhl** [comment]
**pretrained models** can be found here too!
链接：[https://pan.baidu.com/s/14aQkNwLbsKFTA9hdPxMgAA ](https://pan.baidu.com/s/14aQkNwLbsKFTA9hdPxMgAA )
提取码：qw3l 
复制这段内容后打开百度网盘手机App，操作更方便哦

**Comment by yuanxiaode16** [comment]
你好，这个预训练模型是VGG16的，有./checkpoints/enlightening里面需要的预训练模型么？

**Comment by yueruchen** [comment]
@yuanxiaode16 
https://drive.google.com/file/d/1AkV-n2MdyfuZTFvcon8Z4leyVb0i7x63/view

**Comment by 582383982** [comment]
How to modify the contents of opt.txt?After Running the code, I modify the contents of the file to return to the original.

**Comment by TheLissandra1** [comment]
> With the help of other researchers, I succeeded downloading the datasets for EnlightenGAN. Now, I packed them again and upload them to BaiduNetDisk Again. New link is listed below.
> If necessary, contact with me via [fluenceyhl@163.com](mailto:fluenceyhl@163.com).
> 
> 链接：https://pan.baidu.com/s/18JttbhCd5BrMBj_ks-TXNg
> 提取码：k4cb
> 复制这段内容后打开百度网盘手机App，操作更方便哦

The link is not available now, could you please update a new link?

**Comment by cslxiao** [comment]
@hermosayhl , hello, it seems only the training data is included in the shared baidu drive link. Is the testing data available in baidu drive? Thanks

**Comment by tingge23** [comment]
> With the help of other researchers, I succeeded downloading the datasets for EnlightenGAN. Now, I packed them again and upload them to BaiduNetDisk Again. New link is listed below.
> If necessary, contact with me via [fluenceyhl@163.com](mailto:fluenceyhl@163.com).
> 
> 链接：https://pan.baidu.com/s/18JttbhCd5BrMBj_ks-TXNg
> 提取码：k4cb
> 复制这段内容后打开百度网盘手机App，操作更方便哦

Hello, the link is broken, can you share it again?thank you

**Comment by longmiao1s** [comment]
Hello, this link is invalid, can you provide a Baidu cloud link again? If possible, you can try to compress the data before uploading it, and it may not be deleted

**Comment by WMH24** [comment]
@hermosayhl hello,I only found the training data set in the previous link.Could you please provide the test data set or the complete data set link.Thank you.

**Comment by jiefangwanwan** [comment]
你好，此链接无效，能在分享一下吗

**Comment by weinasi-ux** [comment]
求数据集，谢谢你

**Comment by dufu918** [comment]
求数据集连接谢谢

**Comment by dufu918** [comment]
求数据集连接谢谢
