### ISSUE TITLE
Update to newest torch version?

### ISSUE THREAD

**Issue by guantinglin** [TAMU-VITA/EnlightenGAN#31]
Hi, 

Thank for the great work. 

One short question, why did you implement this repo with old version or torch(0.3) instead of new torch(>1.0)? Is there any advantage using old version of torch?

BTW, will you plan to upgrade the code to support newest version of torch?

**Comment by yueruchen** [comment]
This work is done in last years while new version may not have been released. If you need to use new version, just replace all `.data[0]` with `.item()`
