### ISSUE TITLE
Running inference on a single image

### ISSUE THREAD

**Issue by SreeHarshaNelaturu** [TAMU-VITA/EnlightenGAN#32]
Hello --
So my use case is this :
Take in a single input image, run it through EngligtenGAN and get a single input image as output.
A few questions:

1. Is 200_net_G_A.pth only for aligned/unaligned datasets with an input_A and an input_B?
2. In case I'd like to work with a single image, could I work with these weights, or would I need to train my model from scratch?
3. I'm assuming the test model generator for a single image would be unet_256, or is there a different generator I should use.

I'd be grateful for the help.

**Comment by yueruchen** [comment]
To run it on single images, just put your data on `../test_dataset/testA`, and put another whatever image on `../test_dataset/testB`. And run command provided on README.

Default model is enough.

**Comment by SreeHarshaNelaturu** [comment]
Got it, thank you so much! Was able to solve my problem following what you mentioned^
