### ISSUE TITLE
train on other dataset

### ISSUE THREAD

**Issue by lyj0823** [TAMU-VITA/EnlightenGAN#35]

**Comment by lyj0823** [comment]
有没有人试过在别的数据集上训练模型呢？需要注意什么吗，谢谢

**Comment by hermosayhl** [comment]
我试过了！昨天刚试过了
MIT-Adobe FiveK 数据集， ExpertC作为标签， 0-4499 做训练集，4500-5000 做验证集，训练了 95 epoch 得以下结果：
```
opencv_psnr  :   15.675621419654806
mean_psnr  :   28.08877043728922
sklearn_ssim  :   0.7421423059845486
```
虽然客观评测的数据不是很好看，但主观上的增强我觉得是众多方法中较好的！EnlightenGAN 在低光照这方面做得很好，并没有失真啊之类的情况，给几个例子吧：

**Bad Images with low light**

![Snipaste_2020-03-22_15-15-28.png](https://upload-images.jianshu.io/upload_images/11693809-f701e18cb75fbcc6.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

*Enhanced with EnlightenGAN which is trained with Adobe FiveK dataset*

![Snipaste_2020-03-22_15-14-48.png](https://upload-images.jianshu.io/upload_images/11693809-351fa64a0a7f7cce.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

**Comment by hermosayhl** [comment]
些许改动

1. script.py 那里要改数据集的路径，分别命名为 testA 和 testB

2. 要注意数据集中短边最小的长度，因为有个 fineSize 是用来切割图像的，在 script 中修改就可以了

3. 注意测试的图像不能太大，会 OOM 的，我试过了，2000 * 1500 分辨率的图像还是可以的，11G 1080ti。可惜测试这块，作者没有实现多块卡上 Inference，如果可以在低分辨率下增强，作用到高分辨率图像上，就好比 HDRnet 那种就好了

**Comment by yueruchen** [comment]
If I don't misunderstand, your demo has some bugs. The generated image should be added to original images in a residual format while your showed image is not the final one

**Comment by AINIforever** [comment]
请问是否需要修改gpu_ids参数呢

**Comment by TrinhQuocNguyen** [comment]
hermosayhl 
Can you share the dataset you have used (A and B)?

**Comment by loqoella** [comment]
@hermosayhl 
请问在cpu上能跑吗？

**Comment by zhangxiaopang88** [comment]
你是使用自己的低亮度数据集和作者的提供的trainB吗？可以说说您怎么构建您的数据集的吗？我用bdd-100k数据集作为trainA,作者提供的trainB训练，效果还不是很好，可以介绍您除了修改数据集路径还修改哪些参数吗？ @yueruchen @hermosayhl

**Comment by yueruchen** [comment]
@zhangxiaopang88 Could you please provide some examples so that I can help debug? And maybe you could try to tune `-vgg` to adjust your own dataset
