### ISSUE TITLE
Output in testing mode

### ISSUE THREAD

**Issue by alessandroTorresani** [TAMU-VITA/EnlightenGAN#36]
Hi,
thank for sharing this code.
I was trying to execute the algorithm in testing mode using the pre-trained model provided by you.
I prepared two folders, as described by you, and tried with 10 images. I got this output:

_process image... ['../test_dataset/testA/Img_Shutter_03-claheC.png']
process image... ['../test_dataset/testA/Img_Shutter_06-claheC.png']
process image... ['../test_dataset/testA/Img_Shutter_09-claheC.png']
process image... ['../test_dataset/testA/Img_Shutter_12-claheC.png']
process image... ['../test_dataset/testA/Img_Shutter_15-claheC.png']
process image... ['../test_dataset/testA/Img_Shutter_18-claheC.png']
process image... ['../test_dataset/testA/Img_Shutter_21-claheC.png']
process image... ['../test_dataset/testA/Img_Shutter_24-claheC.png']
process image... ['../test_dataset/testA/Img_Shutter_27-claheC.png']
process image... ['../test_dataset/testA/Img_Shutter_30-claheC.png']_

However, I can't find the processed images. Am I doing something wrong?

**Comment by alessandroTorresani** [comment]
Found them, sorry for bothering :)

**Comment by lyp19921126** [comment]
i also can't find result of program?could you tell me the answer,thanks.
