### ISSUE TITLE
Requesting Sampled BDD-100k training images

### ISSUE THREAD

**Issue by KewJieLong** [TAMU-VITA/EnlightenGAN#37]
Hi, can i have the 950 sampled BDD-100k dataset training images? 

If possible, can u share about how u pick the 940 night-time images? There are more than 10k images which have mean pixel intensity smaller than 45. If you can share how you selected the 940 night-time images. that will be super helpful. Thanks !!

**Comment by zhangxiaopang88** [comment]
您好，你找到作者使用的bdd-100k数据了吗？我使用自己选择的bdd-100k数据训练，并没有达到论文中的效果。可能是数据或者其他地方出问题了，请问您的问题解决了吗 @ @KewJieLong @yueruchen

**Comment by yueruchen** [comment]
It is too long to find the sampled BDD-100k data. It should be ok to sample using your own sample strategy.
