### ISSUE TITLE
supplementary materials

### ISSUE THREAD

**Issue by zhangxixi0904** [TAMU-VITA/EnlightenGAN#38]
where can i find the supplementary materials

**Comment by guantinglin** [comment]
Hi, @zhangxixi0904

Did you find it? If yes, can you share it with me? 
Thank you

**Comment by zhangxixi0904** [comment]
> Hi, @zhangxixi0904
> 
> Did you find it? If yes, can you share it with me?
> Thank you

Sorry
I haven’t  found it

**Comment by yueruchen** [comment]
@zhangxixi0904 @guantinglin
The paper is still under review, I'll upload it when it is published. Thanks for your interest!

**Comment by yueruchen** [comment]
https://ieeexplore.ieee.org/document/9334429/media#media
