### ISSUE TITLE
hope it supports pytorch 1.3

### ISSUE THREAD

**Issue by xinheblue** [TAMU-VITA/EnlightenGAN#39]
if pytorch 1.3 is supported, it would be better, otherwise we need to install pytorch 0.3.1 ,otherwise we cann't load the vgg weights

**Comment by bdseal** [comment]
Perhaps you can create isolated python environments by virtualenv.

**Comment by surajpaib** [comment]
I've made a pytorch 1.5 compatible version on this fork: https://github.com/surajpaib/EnlightenGAN
Maybe its useful to you
