### ISSUE TITLE
CycleGAN image enhancement code replication

### ISSUE THREAD

**Issue by crystaloscillator** [TAMU-VITA/EnlightenGAN#40]
Hello author! I reproduced your single model and it was great. I also wanted to reproduce the image enhancement of CycleGAN. I set the model to cycle_gan in script.py, but I ran it with some errors.
I haven't studied the code carefully and want to run through it first. So I want to ask you how you set the parameters for train and predict in script.py. Looking forward to your reply. Thank you very much.

**Comment by yueruchen** [comment]
If you want to reroduce CycleGAN results, I suggest you to directly use CycleGAN code.

**Comment by crystaloscillator** [comment]
By "cycleGAN code",  do you mean another repository? In the models of enlightenGAN ,there are several options, such as cycle_gan, pix2pix, pair, single and so on. Can I use CycleGAN for image enhancement based on your code? Because I saw CycleGAN in your paper to do the contrast effect of image enhancement. If I change the model argument to "cycle_gan" in the EnlightenGAN, can I use CycleGAN for image enhancement? If the code is available, I would like you to tell me the configuration of the other arguments. If not, please tell me about other repositories that use CycleGAN for image enhancement if you know. I'm sorry to bother you, but I really appreciate your code.  It's very systematic. I'm trying to achieve image enhancement in a variety of ways. Thank you very much.

**Comment by yueruchen** [comment]
You can refer to this repo https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix
