### ISSUE TITLE
Unable to reproduce EnlightenGAN-N

### ISSUE THREAD

**Issue by russelltankl** [TAMU-VITA/EnlightenGAN#42]
Hi,

I followed your steps in your paper to reproduce EnlightenGAN-N but with no avail. From my understanding, I just need to swap the training data with BDD-100k low-light images (mean pixel intensity values smaller than 45). Other parameters such as 200 epoch and normal light images remain the same.

Please let me know what am I missing here.

Thanks

**Comment by yueruchen** [comment]
You should upload some results then I can help debug

**Comment by russelltankl** [comment]
My apologies for taking so long to reply. Here are a few sample images I have. 
The results of enhancement from my end have a lot of artifacts around light sources.

![Capture](https://user-images.githubusercontent.com/31522924/81828558-89576980-94ff-11ea-8dee-987372b9131a.PNG)

![Capture](https://user-images.githubusercontent.com/31522924/81828646-9ffdc080-94ff-11ea-9d5b-e0fbaeda9189.PNG)

![Capture](https://user-images.githubusercontent.com/31522924/81828699-b1df6380-94ff-11ea-8a00-57f2a65de348.PNG)

**Comment by yueruchen** [comment]
Do you use the dark dataset in BDD-100k and bright dataset from what I provided?

**Comment by russelltankl** [comment]
Yes I did for both. More specifically I used images from BDD-100k that are labeled as "night" in the labels.

Do you know what is causing this artifact, or how to move forward from here to troubleshoot the problem?

**Comment by zhangxiaopang88** [comment]
我也用bdd-100k数据集去训练，我想问您说低亮度数据集使用自己的，正常光数据集使用您提供的1016张图片，那我自己低亮度的数据个数有限制吗，对低亮度的图片还有其他要求吗？非常期待您 的回复 @yueruchen

**Comment by yueruchen** [comment]
I'm really busy over the last month. Have you solved the problems? @zhangxiaopang88 @russelltankl

**Comment by yueruchen** [comment]
@zhangxiaopang88 If you want to use your own dataset, you should confirm that 1) the dataset you prepared is not extremely dark, which is not suitable in our case due to severe noise. 2) prepare ~1000 data should be enough

**Comment by russelltankl** [comment]
@yueruchen I have not solved it yet. Currently, I'm not sure how to proceed

**Comment by yueruchen** [comment]
Could you please slightly enlarge the self_feature_preserving_loss `--vgg` ?
Normally we use gan loss and vgg loss to balance the brightness and naturalness. Seems that your results show that you make it too much bright, so you should increase the `--vgg` loss weight.
