### ISSUE TITLE
The link to google drive2 is not working

### ISSUE THREAD

**Issue by moopene36607** [TAMU-VITA/EnlightenGAN#46]
"Download VGG pretrained model from [Google Drive 1], [2] and then put them into the directory model."
The second link is not working.

**Comment by yueruchen** [comment]
Google drive 1 should be enough. If you look at the code https://github.com/TAMU-VITA/EnlightenGAN/blob/eda2e214802b8adca8019404c09e645f4629b758/models/networks.py#L1039
only when google drive 2 is missing we need google drive 2

**Comment by yueruchen** [comment]
I just push a new commit, you can refer to that
