### ISSUE TITLE
Pretrained Discriminator for Continued Training

### ISSUE THREAD

**Issue by surajpaib** [TAMU-VITA/EnlightenGAN#48]
Thank you for sharing this great project! 
I've been working for the past week on experimenting with your codebase and trying out object-specific enhancement on the Exclusively Dark Dataset. I do have some decent results but they do not look qualitatively the same as the ones from the Arxiv paper for the domain adapted BBD dataset.

I'd like to try continued training on the EnlightenGAN but can't seem to find the Discriminator weights. Would you mind pointing me in the right direction or sharing these weights if they aren't public?

**Comment by yueruchen** [comment]
Actually I can not find the discriminators weights now. Normally if you set the dark dataset using your data and set bright dataset using the dataset I provided, you should be able to reproduce the results following the README guideline.

**Comment by surajpaib** [comment]
@yueruchen  No problem! Just wanted to see if these files exist somewhere so that I can easily plug and play to continue training. Thanks for checking.

Closing the issue now
