### ISSUE TITLE
training error

### ISSUE THREAD

**Issue by jeighfrost** [TAMU-VITA/EnlightenGAN#51]
I always get this kind of errors every time I train. How do I resolve this?

  File "/home/jef.silang/.conda/envs/jepwey/lib/python3.5/random.py", line 205, in randrange
    raise ValueError("empty range for randrange() (%d,%d, %d)" % (istart, istop, width))
ValueError: empty range for randrange() (0,-60, -60)

and this one

ConnectionRefusedError: [Errno 111] Connection refused

**Comment by yueruchen** [comment]
For the first one, you should make sure your data resolution is larger than the cropped images.
For the second one, you should launch `python -m visdom.server` in another terminal.
