### ISSUE TITLE
Grayscale Attention Map Calculation

### ISSUE THREAD

**Issue by DomhnallBoyle** [TAMU-VITA/EnlightenGAN#54]
Is this the code used to generate the grayscale attention map?

```
r,g,b = input_img[0]+1, input_img[1]+1, input_img[2]+1
A_gray = 1. - (0.299*r+0.587*g+0.114*b)/2.
```

Where was this formula derived from? It looks like some weighted/luminance based method

Thanks

**Comment by yueruchen** [comment]
You can refer to this link: https://en.wikipedia.org/wiki/Grayscale
