### ISSUE TITLE
Problems with latent_show latent_real_A fake_B

### ISSUE THREAD

**Issue by UnParKs** [TAMU-VITA/EnlightenGAN#58]
I have finished the training process but I dt ecactly know the meaning of latent_show and latent_real_A.I know one uses tensor2im and the other uses latent2im。Can you tell me the difference between latent_show and fake_B? Thanks a lot

**Comment by yueruchen** [comment]
fake_B = input + latent_show

**Comment by UnParKs** [comment]
for the code output = latent + input*self.opt.skip ?

**Comment by yueruchen** [comment]
yes

**Comment by UnParKs** [comment]
Thanks

**Comment by UnParKs** [comment]
By the way,whats the difference between  latent_realA and lantent_show?thx

**Comment by UnParKs** [comment]
By the way,whats the difference between  latent_realA and lantent_show?thx
