### ISSUE TITLE
Attention map calculation

### ISSUE THREAD

**Issue by sadik1111** [TAMU-VITA/EnlightenGAN#59]
In the process of attention map calculation,  why should all channel  be added with 1 and divided with 2？Are these operation desinged to norm the  value of pixel to [0,1]？Thanks for any help
`r,g,b = input_img[0]+1, input_img[1]+1, input_img[2]+1
A_gray = 1. - (0.299*r+0.587*g+0.114*b)/2.`

**Comment by yueruchen** [comment]
yes, [-1, 1] to [0,1]

**Comment by sadik1111** [comment]
> yes, [-1, 1] to [0,1]

thanks for your answer
